{% set version = "0.5.9" %}
{% set python_min = "3.9" %}

package:
  name: mkgraticule-planet
  version: {{ version }}

source:
  url: https://github.com/ryodohemmi/mkgraticule_planet/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 701d6c700a8fb9e6637a4ccb9a27ee07def403af9a558e40be8096937ba35173

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - mkgraticule_planet = mkgraticule_planet._cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=68.0
  run:
    - python >={{ python_min }}
    - numpy
    - gdal

test:
  requires:
    - python {{ python_min }}
  imports:
    - mkgraticule_planet
  commands:
    - mkgraticule_planet --version
    - mkgraticule_planet --help

about:
  home: https://github.com/ryodohemmi/mkgraticule_planet
  summary: Create planetary graticules for IAU coordinate systems and export as GeoPackage
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ryodohemmi
